import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { useState } from "react";

// Components
import Form from "../components/Form";
import DataCard from "@/components/DataCard";
import SchemaCard from "@/components/SchemaCard";
import PHChart from "@/components/PHChart";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [fill, setFill] = useState(3);

  function changeFillHandler() {
    setFill(Math.round(Math.random() * 14));
  }
  return (
    <main className="max-w-7xl mx-auto fir">
      {/* Main header. */}
      <header className="py-32">
        <h1 className="text-center max-w-3xl mx-auto">
          Potężna aplikacja webowa.
        </h1>
      </header>
      {/* Insert data to calculate. */}
      <section className="flex justify-center items-center mb-36">
        <Form />
      </section>
      {/* Printed data. */}
      <section className="mb-10">
        {/* Data */}
        <div className="grid grid-cols-3 gap-10">
          <DataCard title="Masa" data="10" />
          <DataCard title="Masa" data="10" />
          <DataCard title="Masa" data="10" />
        </div>
        {/* PH chart */}
        <div className="my-10">
          <button onClick={changeFillHandler}>Change fill</button>
          <PHChart fill={fill} />
        </div>
        {/* Schema */}
        <div>
          <SchemaCard />
        </div>
      </section>
    </main>
  );
}

// export default function Home() {
//   // fetch("/endpoint")
//   //   .then((response) => response.json())
//   //   .then((data) => {})
//   //   .catch((error) => {});

//   const [value, setValue] = useState<string>("");
//   function changeHandler(e: any) {
//     setValue(e.target.value);
//   }
//   function submitHandler(e: any) {
//     e.preventDefault();
//     console.log("submitted");
// 	let value = 'genome="accc"'

//     fetch("/api/data", {
//       method: "POST",
//       headers: {
//         "Content-Type": "application/x-www-form-urlencoded",
//       },
//       body: value,
//     })
//       .then((response) => response.json())
//       .then((data) => {
//         // button.disabled = false;
//         console.log("Success:", data);
//         let { Ok: status = false, Message: message } = data;

//         // account balance
//         if (status === true) {
//           // document.querySelector("#coins").innerText = message;
//           // notification("Zakupiono przedmiot!", "success");
//         } else {
//           // notification(message, "error");
//         }
//       });

//     // .catch((error) => {
//     //   button.disabled = false;
//     //   console.error("Error:", error);
//     //   notification("Wystąpił błąd!", "error");
//     // });
//   }
//   return (
//     <>
//       <h1 className="text-7xl text-red-300">hohoo</h1>
//       <form
//         action=""
//         onChange={changeHandler}
//         className="bg-red-300 p-10"
//         onSubmit={submitHandler}
//       >
//         <input type="text" name="" />
//         <button>submit</button>
//       </form>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className={styles.main}>
//         <div className={styles.description}>
//           <p>
//             Get started by editing&nbsp;
//             <code className={styles.code}>pages/index.tsx</code>
//           </p>
//           <div>
//             <a
//               href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//               target="_blank"
//               rel="noopener noreferrer"
//             >
//               By{" "}
//               <Image
//                 src="/vercel.svg"
//                 alt="Vercel Logo"
//                 className={styles.vercelLogo}
//                 width={100}
//                 height={24}
//                 priority
//               />
//             </a>
//           </div>
//         </div>

//         <div className={styles.center}>
//           <Image
//             className={styles.logo}
//             src="/next.svg"
//             alt="Next.js Logo"
//             width={180}
//             height={37}
//             priority
//           />
//           <div className={styles.thirteen}>
//             <Image
//               src="/thirteen.svg"
//               alt="13"
//               width={40}
//               height={31}
//               priority
//             />
//           </div>
//         </div>

//         <div className={styles.grid}>
//           <a
//             href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Docs <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Find in-depth information about Next.js features and&nbsp;API.
//             </p>
//           </a>

//           <a
//             href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Learn <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Learn about Next.js in an interactive course with&nbsp;quizzes!
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Templates <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Discover and deploy boilerplate example Next.js&nbsp;projects.
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Deploy <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Instantly deploy your Next.js site to a shareable URL
//               with&nbsp;Vercel.
//             </p>
//           </a>
//         </div>
//       </main>
//     </>
//   );
// }
