import type { NextApiRequest, NextApiResponse } from 'next'

export default function handler(req,res) {
    res.status(200).setHeader("Content-type", "image/svg+xml").send(`<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by SVGo -->
<svg width="3450" height="340" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<text x="35" y="167" style="stroke:black">H</text>
<text x="43" y="155" style="stroke:black">+</text>
<text x="49" y="167" style="stroke:black;font-size:8px">2</text>
<text x="54" y="167" style="stroke:black">N</text>
<text x="54" y="152" style="stroke:black">H</text>
<clipPath id="gmxjgtapgaulmodzlvmgvrdixxmnppri"><polyline points="62,167 90,185 58,173" style="stroke:black;stroke-width:0;fill:black"/>
</clipPath>
<line x1="58" y1="173" x2="62" y2="167" style="stroke: black;stroke-width:3px;clip-path:url(#gmxjgtapgaulmodzlvmgvrdixxmnppri)"/>
<line x1="64" y1="176" x2="68" y2="170" style="stroke: black;stroke-width:3px;clip-path:url(#gmxjgtapgaulmodzlvmgvrdixxmnppri)"/>
<line x1="70" y1="179" x2="74" y2="173" style="stroke: black;stroke-width:3px;clip-path:url(#gmxjgtapgaulmodzlvmgvrdixxmnppri)"/>
<line x1="76" y1="182" x2="80" y2="176" style="stroke: black;stroke-width:3px;clip-path:url(#gmxjgtapgaulmodzlvmgvrdixxmnppri)"/>
<line x1="82" y1="185" x2="86" y2="179" style="stroke: black;stroke-width:3px;clip-path:url(#gmxjgtapgaulmodzlvmgvrdixxmnppri)"/>
<line x1="90" y1="185" x2="120" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="118" y1="170" x2="118" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="122" y1="170" x2="122" y2="140" style="stroke:black;stroke-width:2px"/>
<text x="114" y="137" style="stroke:black">O</text>
<line x1="120" y1="170" x2="150" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="90" y1="185" x2="90" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="90" y1="215" x2="120" y2="230" style="stroke:black;stroke-width:2px"/>
<line x1="120" y1="230" x2="120" y2="260" style="stroke:black;stroke-width:2px"/>
<text x="114" y="275" style="stroke:black">S</text>
<line x1="120" y1="260" x2="150" y2="275" style="stroke:black;stroke-width:2px"/>
<text x="144" y="200" style="stroke:black">N</text>
<text x="144" y="215" style="stroke:black">H</text>
<polyline points="152,188 180,170 148,182" style="stroke:black;stroke-width:0;fill:black"/>
<line x1="180" y1="170" x2="210" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="208" y1="185" x2="208" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="212" y1="185" x2="212" y2="215" style="stroke:black;stroke-width:2px"/>
<text x="204" y="230" style="stroke:black">O</text>
<line x1="210" y1="185" x2="240" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="180" y1="170" x2="180" y2="140" style="stroke:black;stroke-width:2px"/>
<polyline points="152,122 180,140 148,128" style="stroke:black;stroke-width:0;fill:black"/>
<line x1="180" y1="140" x2="210" y2="125" style="stroke:black;stroke-width:2px"/>
<line x1="210" y1="125" x2="210" y2="95" style="stroke:black;stroke-width:2px"/>
<text x="234" y="167" style="stroke:black">N</text>
<text x="234" y="152" style="stroke:black">H</text>
<clipPath id="mgegmgkbnpunixdzjdhwozafnndfbkfg"><polyline points="242,167 270,185 238,173" style="stroke:black;stroke-width:0;fill:black"/>
</clipPath>
<line x1="238" y1="173" x2="242" y2="167" style="stroke: black;stroke-width:3px;clip-path:url(#mgegmgkbnpunixdzjdhwozafnndfbkfg)"/>
<line x1="244" y1="176" x2="248" y2="170" style="stroke: black;stroke-width:3px;clip-path:url(#mgegmgkbnpunixdzjdhwozafnndfbkfg)"/>
<line x1="250" y1="179" x2="254" y2="173" style="stroke: black;stroke-width:3px;clip-path:url(#mgegmgkbnpunixdzjdhwozafnndfbkfg)"/>
<line x1="256" y1="182" x2="260" y2="176" style="stroke: black;stroke-width:3px;clip-path:url(#mgegmgkbnpunixdzjdhwozafnndfbkfg)"/>
<line x1="262" y1="185" x2="266" y2="179" style="stroke: black;stroke-width:3px;clip-path:url(#mgegmgkbnpunixdzjdhwozafnndfbkfg)"/>
<line x1="270" y1="185" x2="300" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="298" y1="170" x2="298" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="302" y1="170" x2="302" y2="140" style="stroke:black;stroke-width:2px"/>
<text x="294" y="137" style="stroke:black">O</text>
<line x1="300" y1="170" x2="330" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="270" y1="185" x2="270" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="270" y1="215" x2="300" y2="230" style="stroke:black;stroke-width:2px"/>
<line x1="300" y1="230" x2="300" y2="260" style="stroke:black;stroke-width:2px"/>
<line x1="300" y1="260" x2="330" y2="275" style="stroke:black;stroke-width:2px"/>
<text x="333" y="282" style="stroke:black">N</text>
<text x="343" y="282" style="stroke:black">H</text>
<line x1="328" y1="275" x2="328" y2="305" style="stroke:black;stroke-width:2px"/>
<line x1="332" y1="275" x2="332" y2="281" style="stroke:black;stroke-width:2px"/>
<line x1="332" y1="287" x2="332" y2="293" style="stroke:black;stroke-width:2px"/>
<line x1="332" y1="299" x2="332" y2="305" style="stroke:black;stroke-width:2px"/>
<line x1="328" y1="307" x2="298" y2="322" style="stroke:black;stroke-width:2px"/>
<text x="284" y="327" style="stroke:black">N</text>
<text x="278" y="327" style="font-size:8px;stroke:black">2</text>
<text x="264" y="327" style="stroke:black">H</text>
<line x1="328" y1="303" x2="322" y2="306" style="stroke:black;stroke-width:2px"/>
<line x1="316" y1="309" x2="310" y2="312" style="stroke:black;stroke-width:2px"/>
<line x1="304" y1="315" x2="298" y2="318" style="stroke:black;stroke-width:2px"/>
<line x1="330" y1="303" x2="360" y2="318" style="stroke:black;stroke-width:2px"/>
<text x="361" y="327" style="stroke:black">N</text>
<text x="371" y="327" style="stroke:black">H</text>
<text x="385" y="327" style="font-size:8px;stroke:black">2</text>
<line x1="328" y1="307" x2="334" y2="310" style="stroke:black;stroke-width:2px"/>
<line x1="340" y1="313" x2="346" y2="316" style="stroke:black;stroke-width:2px"/>
<line x1="352" y1="319" x2="358" y2="322" style="stroke:black;stroke-width:2px"/>
<circle cx="328" cy="305" r="8" style="fill:white;stroke:black;stroke-width:2px"/>
<text x="328" y="309" style="stroke:black;text-anchor:middle">+</text>
<text x="324" y="200" style="stroke:black">N</text>
<text x="324" y="215" style="stroke:black">H</text>
<polyline points="332,188 360,170 328,182" style="stroke:black;stroke-width:0;fill:black"/>
<line x1="360" y1="170" x2="390" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="388" y1="185" x2="388" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="392" y1="185" x2="392" y2="215" style="stroke:black;stroke-width:2px"/>
<text x="384" y="230" style="stroke:black">O</text>
<line x1="390" y1="185" x2="420" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="360" y1="170" x2="360" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="360" y1="140" x2="390" y2="125" style="stroke:black;stroke-width:2px"/>
<line x1="390" y1="125" x2="390" y2="95" style="stroke:black;stroke-width:2px"/>
<line x1="390" y1="125" x2="420" y2="125" style="stroke:black;stroke-width:2px"/>
<text x="414" y="167" style="stroke:black">N</text>
<text x="414" y="152" style="stroke:black">H</text>
<line x1="420" y1="170" x2="450" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="450" y1="185" x2="480" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="478" y1="170" x2="478" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="482" y1="170" x2="482" y2="140" style="stroke:black;stroke-width:2px"/>
<text x="474" y="137" style="stroke:black">O</text>
<line x1="480" y1="170" x2="510" y2="185" style="stroke:black;stroke-width:2px"/>
<text x="504" y="200" style="stroke:black">N</text>
<text x="504" y="215" style="stroke:black">H</text>
<polyline points="512,188 540,170 508,182" style="stroke:black;stroke-width:0;fill:black"/>
<line x1="540" y1="170" x2="570" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="568" y1="185" x2="568" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="572" y1="185" x2="572" y2="215" style="stroke:black;stroke-width:2px"/>
<text x="564" y="230" style="stroke:black">O</text>
<line x1="570" y1="185" x2="600" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="540" y1="170" x2="540" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="540" y1="140" x2="570" y2="125" style="stroke:black;stroke-width:2px"/>
<line x1="570" y1="125" x2="600" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="602" y1="134" x2="626" y2="122" style="stroke:black;stroke-width:2px"/>
<line x1="600" y1="140" x2="630" y2="125" style="stroke:black;stroke-width:2px"/>
<line x1="630" y1="125" x2="630" y2="95" style="stroke:black;stroke-width:2px"/>
<line x1="626" y1="98" x2="602" y2="86" style="stroke:black;stroke-width:2px"/>
<line x1="630" y1="95" x2="600" y2="80" style="stroke:black;stroke-width:2px"/>
<line x1="600" y1="80" x2="570" y2="95" style="stroke:black;stroke-width:2px"/>
<line x1="574" y1="98" x2="574" y2="122" style="stroke:black;stroke-width:2px"/>
<line x1="570" y1="95" x2="570" y2="125" style="stroke:black;stroke-width:2px"/>
<line x1="630" y1="95" x2="660" y2="80" style="stroke:black;stroke-width:2px"/>
<text x="663" y="87" style="stroke:black">O</text>
<text x="673" y="87" style="stroke:black">H</text>
<text x="594" y="167" style="stroke:black">N</text>
<text x="594" y="152" style="stroke:black">H</text>
<clipPath id="rdlciwnbctxucnwvydmirjitrcdlwhpd"><polyline points="602,167 630,185 598,173" style="stroke:black;stroke-width:0;fill:black"/>
</clipPath>
<line x1="598" y1="173" x2="602" y2="167" style="stroke: black;stroke-width:3px;clip-path:url(#rdlciwnbctxucnwvydmirjitrcdlwhpd)"/>
<line x1="604" y1="176" x2="608" y2="170" style="stroke: black;stroke-width:3px;clip-path:url(#rdlciwnbctxucnwvydmirjitrcdlwhpd)"/>
<line x1="610" y1="179" x2="614" y2="173" style="stroke: black;stroke-width:3px;clip-path:url(#rdlciwnbctxucnwvydmirjitrcdlwhpd)"/>
<line x1="616" y1="182" x2="620" y2="176" style="stroke: black;stroke-width:3px;clip-path:url(#rdlciwnbctxucnwvydmirjitrcdlwhpd)"/>
<line x1="622" y1="185" x2="626" y2="179" style="stroke: black;stroke-width:3px;clip-path:url(#rdlciwnbctxucnwvydmirjitrcdlwhpd)"/>
<line x1="630" y1="185" x2="660" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="658" y1="170" x2="658" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="662" y1="170" x2="662" y2="140" style="stroke:black;stroke-width:2px"/>
<text x="654" y="137" style="stroke:black">O</text>
<line x1="660" y1="170" x2="690" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="630" y1="185" x2="630" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="630" y1="215" x2="660" y2="230" style="stroke:black;stroke-width:2px"/>
<line x1="660" y1="230" x2="660" y2="260" style="stroke:black;stroke-width:2px"/>
<line x1="660" y1="260" x2="690" y2="275" style="stroke:black;stroke-width:2px"/>
<line x1="690" y1="275" x2="690" y2="305" style="stroke:black;stroke-width:2px"/>
<text x="693" y="312" style="stroke:black">N</text>
<text x="703" y="312" style="stroke:black">H</text>
<text x="717" y="312" style="font-size:8px;stroke:black">3</text>
<text x="684" y="320" style="stroke:black">+</text>
<text x="684" y="200" style="stroke:black">N</text>
<text x="684" y="215" style="stroke:black">H</text>
<polyline points="692,188 720,170 688,182" style="stroke:black;stroke-width:0;fill:black"/>
<line x1="720" y1="170" x2="750" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="748" y1="185" x2="748" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="752" y1="185" x2="752" y2="215" style="stroke:black;stroke-width:2px"/>
<text x="744" y="230" style="stroke:black">O</text>
<line x1="750" y1="185" x2="780" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="720" y1="170" x2="720" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="720" y1="140" x2="750" y2="125" style="stroke:black;stroke-width:2px"/>
<line x1="750" y1="125" x2="780" y2="125" style="stroke:black;stroke-width:2px"/>
<text x="783" y="132" style="stroke:black">N</text>
<text x="793" y="132" style="stroke:black">H</text>
<text x="807" y="132" style="font-size:8px;stroke:black">2</text>
<line x1="748" y1="125" x2="748" y2="95" style="stroke:black;stroke-width:2px"/>
<line x1="752" y1="125" x2="752" y2="95" style="stroke:black;stroke-width:2px"/>
<text x="744" y="92" style="stroke:black">O</text>
<text x="774" y="167" style="stroke:black">N</text>
<text x="774" y="152" style="stroke:black">H</text>
<clipPath id="ctfyabphmkkkphydrhjxsmwubcgervtl"><polyline points="782,167 810,185 778,173" style="stroke:black;stroke-width:0;fill:black"/>
</clipPath>
<line x1="778" y1="173" x2="782" y2="167" style="stroke: black;stroke-width:3px;clip-path:url(#ctfyabphmkkkphydrhjxsmwubcgervtl)"/>
<line x1="784" y1="176" x2="788" y2="170" style="stroke: black;stroke-width:3px;clip-path:url(#ctfyabphmkkkphydrhjxsmwubcgervtl)"/>
<line x1="790" y1="179" x2="794" y2="173" style="stroke: black;stroke-width:3px;clip-path:url(#ctfyabphmkkkphydrhjxsmwubcgervtl)"/>
<line x1="796" y1="182" x2="800" y2="176" style="stroke: black;stroke-width:3px;clip-path:url(#ctfyabphmkkkphydrhjxsmwubcgervtl)"/>
<line x1="802" y1="185" x2="806" y2="179" style="stroke: black;stroke-width:3px;clip-path:url(#ctfyabphmkkkphydrhjxsmwubcgervtl)"/>
<line x1="810" y1="185" x2="840" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="838" y1="170" x2="838" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="842" y1="170" x2="842" y2="140" style="stroke:black;stroke-width:2px"/>
<text x="834" y="137" style="stroke:black">O</text>
<line x1="840" y1="170" x2="870" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="810" y1="185" x2="810" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="810" y1="215" x2="840" y2="230" style="stroke:black;stroke-width:2px"/>
<line x1="840" y1="230" x2="840" y2="260" style="stroke:black;stroke-width:2px"/>
<line x1="840" y1="230" x2="870" y2="230" style="stroke:black;stroke-width:2px"/>
<text x="864" y="200" style="stroke:black">N</text>
<text x="864" y="215" style="stroke:black">H</text>
<polyline points="872,188 900,170 868,182" style="stroke:black;stroke-width:0;fill:black"/>
<line x1="900" y1="170" x2="930" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="928" y1="185" x2="928" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="932" y1="185" x2="932" y2="215" style="stroke:black;stroke-width:2px"/>
<text x="924" y="230" style="stroke:black">O</text>
<line x1="930" y1="185" x2="960" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="900" y1="170" x2="900" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="900" y1="140" x2="930" y2="125" style="stroke:black;stroke-width:2px"/>
<line x1="930" y1="125" x2="960" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="962" y1="134" x2="986" y2="122" style="stroke:black;stroke-width:2px"/>
<line x1="960" y1="140" x2="990" y2="125" style="stroke:black;stroke-width:2px"/>
<line x1="990" y1="125" x2="990" y2="95" style="stroke:black;stroke-width:2px"/>
<line x1="986" y1="98" x2="962" y2="86" style="stroke:black;stroke-width:2px"/>
<line x1="990" y1="95" x2="960" y2="80" style="stroke:black;stroke-width:2px"/>
<line x1="960" y1="80" x2="930" y2="95" style="stroke:black;stroke-width:2px"/>
<line x1="934" y1="98" x2="934" y2="122" style="stroke:black;stroke-width:2px"/>
<line x1="930" y1="95" x2="930" y2="125" style="stroke:black;stroke-width:2px"/>
<line x1="990" y1="95" x2="1020" y2="80" style="stroke:black;stroke-width:2px"/>
<text x="1023" y="87" style="stroke:black">O</text>
<text x="1033" y="87" style="stroke:black">H</text>
<text x="954" y="167" style="stroke:black">N</text>
<text x="954" y="152" style="stroke:black">H</text>
<clipPath id="ugcakkmzdtjdzxmhroplbbpbuofibpci"><polyline points="962,167 990,185 958,173" style="stroke:black;stroke-width:0;fill:black"/>
</clipPath>
<line x1="958" y1="173" x2="962" y2="167" style="stroke: black;stroke-width:3px;clip-path:url(#ugcakkmzdtjdzxmhroplbbpbuofibpci)"/>
<line x1="964" y1="176" x2="968" y2="170" style="stroke: black;stroke-width:3px;clip-path:url(#ugcakkmzdtjdzxmhroplbbpbuofibpci)"/>
<line x1="970" y1="179" x2="974" y2="173" style="stroke: black;stroke-width:3px;clip-path:url(#ugcakkmzdtjdzxmhroplbbpbuofibpci)"/>
<line x1="976" y1="182" x2="980" y2="176" style="stroke: black;stroke-width:3px;clip-path:url(#ugcakkmzdtjdzxmhroplbbpbuofibpci)"/>
<line x1="982" y1="185" x2="986" y2="179" style="stroke: black;stroke-width:3px;clip-path:url(#ugcakkmzdtjdzxmhroplbbpbuofibpci)"/>
<line x1="990" y1="185" x2="1020" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="1018" y1="170" x2="1018" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="1022" y1="170" x2="1022" y2="140" style="stroke:black;stroke-width:2px"/>
<text x="1014" y="137" style="stroke:black">O</text>
<line x1="1020" y1="170" x2="1050" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="990" y1="185" x2="990" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="990" y1="215" x2="1020" y2="230" style="stroke:black;stroke-width:2px"/>
<line x1="1020" y1="230" x2="1020" y2="260" style="stroke:black;stroke-width:2px"/>
<line x1="1020" y1="260" x2="1050" y2="275" style="stroke:black;stroke-width:2px"/>
<line x1="1050" y1="275" x2="1050" y2="305" style="stroke:black;stroke-width:2px"/>
<text x="1053" y="312" style="stroke:black">N</text>
<text x="1063" y="312" style="stroke:black">H</text>
<text x="1077" y="312" style="font-size:8px;stroke:black">3</text>
<text x="1044" y="320" style="stroke:black">+</text>
<text x="1044" y="200" style="stroke:black">N</text>
<text x="1044" y="215" style="stroke:black">H</text>
<polyline points="1052,188 1080,170 1048,182" style="stroke:black;stroke-width:0;fill:black"/>
<line x1="1080" y1="170" x2="1110" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="1108" y1="185" x2="1108" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="1112" y1="185" x2="1112" y2="215" style="stroke:black;stroke-width:2px"/>
<text x="1104" y="230" style="stroke:black">O</text>
<line x1="1110" y1="185" x2="1140" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="1080" y1="170" x2="1080" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="1080" y1="140" x2="1110" y2="125" style="stroke:black;stroke-width:2px"/>
<line x1="1110" y1="125" x2="1140" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="1142" y1="134" x2="1166" y2="122" style="stroke:black;stroke-width:2px"/>
<line x1="1140" y1="140" x2="1170" y2="125" style="stroke:black;stroke-width:2px"/>
<line x1="1170" y1="125" x2="1170" y2="95" style="stroke:black;stroke-width:2px"/>
<line x1="1166" y1="98" x2="1142" y2="86" style="stroke:black;stroke-width:2px"/>
<line x1="1170" y1="95" x2="1140" y2="80" style="stroke:black;stroke-width:2px"/>
<line x1="1140" y1="80" x2="1110" y2="95" style="stroke:black;stroke-width:2px"/>
<line x1="1114" y1="98" x2="1114" y2="122" style="stroke:black;stroke-width:2px"/>
<line x1="1110" y1="95" x2="1110" y2="125" style="stroke:black;stroke-width:2px"/>
<line x1="1170" y1="95" x2="1200" y2="80" style="stroke:black;stroke-width:2px"/>
<text x="1203" y="87" style="stroke:black">O</text>
<text x="1213" y="87" style="stroke:black">H</text>
<text x="1134" y="167" style="stroke:black">N</text>
<text x="1134" y="152" style="stroke:black">H</text>
<clipPath id="sgdexysittrkkpemhpwofnajvivjxkpm"><polyline points="1142,167 1170,185 1138,173" style="stroke:black;stroke-width:0;fill:black"/>
</clipPath>
<line x1="1138" y1="173" x2="1142" y2="167" style="stroke: black;stroke-width:3px;clip-path:url(#sgdexysittrkkpemhpwofnajvivjxkpm)"/>
<line x1="1144" y1="176" x2="1148" y2="170" style="stroke: black;stroke-width:3px;clip-path:url(#sgdexysittrkkpemhpwofnajvivjxkpm)"/>
<line x1="1150" y1="179" x2="1154" y2="173" style="stroke: black;stroke-width:3px;clip-path:url(#sgdexysittrkkpemhpwofnajvivjxkpm)"/>
<line x1="1156" y1="182" x2="1160" y2="176" style="stroke: black;stroke-width:3px;clip-path:url(#sgdexysittrkkpemhpwofnajvivjxkpm)"/>
<line x1="1162" y1="185" x2="1166" y2="179" style="stroke: black;stroke-width:3px;clip-path:url(#sgdexysittrkkpemhpwofnajvivjxkpm)"/>
<line x1="1170" y1="185" x2="1200" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="1198" y1="170" x2="1198" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="1202" y1="170" x2="1202" y2="140" style="stroke:black;stroke-width:2px"/>
<text x="1194" y="137" style="stroke:black">O</text>
<line x1="1200" y1="170" x2="1230" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="1170" y1="185" x2="1170" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="1170" y1="215" x2="1200" y2="230" style="stroke:black;stroke-width:2px"/>
<line x1="1200" y1="230" x2="1200" y2="260" style="stroke:black;stroke-width:2px"/>
<line x1="1200" y1="230" x2="1230" y2="230" style="stroke:black;stroke-width:2px"/>
<text x="1224" y="200" style="stroke:black">N</text>
<text x="1224" y="215" style="stroke:black">H</text>
<polyline points="1232,188 1260,170 1228,182" style="stroke:black;stroke-width:0;fill:black"/>
<line x1="1260" y1="170" x2="1290" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="1288" y1="185" x2="1288" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="1292" y1="185" x2="1292" y2="215" style="stroke:black;stroke-width:2px"/>
<text x="1284" y="230" style="stroke:black">O</text>
<line x1="1290" y1="185" x2="1320" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="1260" y1="170" x2="1260" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="1260" y1="140" x2="1290" y2="125" style="stroke:black;stroke-width:2px"/>
<line x1="1290" y1="125" x2="1320" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="1322" y1="134" x2="1346" y2="122" style="stroke:black;stroke-width:2px"/>
<line x1="1320" y1="140" x2="1350" y2="125" style="stroke:black;stroke-width:2px"/>
<line x1="1350" y1="125" x2="1350" y2="95" style="stroke:black;stroke-width:2px"/>
<line x1="1346" y1="98" x2="1322" y2="86" style="stroke:black;stroke-width:2px"/>
<line x1="1350" y1="95" x2="1320" y2="80" style="stroke:black;stroke-width:2px"/>
<line x1="1320" y1="80" x2="1290" y2="95" style="stroke:black;stroke-width:2px"/>
<line x1="1294" y1="98" x2="1294" y2="122" style="stroke:black;stroke-width:2px"/>
<line x1="1290" y1="95" x2="1290" y2="125" style="stroke:black;stroke-width:2px"/>
<text x="1314" y="167" style="stroke:black">N</text>
<text x="1314" y="152" style="stroke:black">H</text>
<clipPath id="evygvragesgclvzmxsnldntguhhcagdv"><polyline points="1322,167 1350,185 1318,173" style="stroke:black;stroke-width:0;fill:black"/>
</clipPath>
<line x1="1318" y1="173" x2="1322" y2="167" style="stroke: black;stroke-width:3px;clip-path:url(#evygvragesgclvzmxsnldntguhhcagdv)"/>
<line x1="1324" y1="176" x2="1328" y2="170" style="stroke: black;stroke-width:3px;clip-path:url(#evygvragesgclvzmxsnldntguhhcagdv)"/>
<line x1="1330" y1="179" x2="1334" y2="173" style="stroke: black;stroke-width:3px;clip-path:url(#evygvragesgclvzmxsnldntguhhcagdv)"/>
<line x1="1336" y1="182" x2="1340" y2="176" style="stroke: black;stroke-width:3px;clip-path:url(#evygvragesgclvzmxsnldntguhhcagdv)"/>
<line x1="1342" y1="185" x2="1346" y2="179" style="stroke: black;stroke-width:3px;clip-path:url(#evygvragesgclvzmxsnldntguhhcagdv)"/>
<line x1="1350" y1="185" x2="1380" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="1378" y1="170" x2="1378" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="1382" y1="170" x2="1382" y2="140" style="stroke:black;stroke-width:2px"/>
<text x="1374" y="137" style="stroke:black">O</text>
<line x1="1380" y1="170" x2="1410" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="1350" y1="185" x2="1350" y2="215" style="stroke:black;stroke-width:2px"/>
<clipPath id="stvwlhvkxelkveeokbghraomilekjpuo"><polyline points="1322,233 1350,215 1318,227" style="stroke:black;stroke-width:0;fill:black"/>
</clipPath>
<line x1="1348" y1="212" x2="1352" y2="218" style="stroke: black;stroke-width:3px;clip-path:url(#stvwlhvkxelkveeokbghraomilekjpuo)"/>
<line x1="1342" y1="215" x2="1346" y2="221" style="stroke: black;stroke-width:3px;clip-path:url(#stvwlhvkxelkveeokbghraomilekjpuo)"/>
<line x1="1336" y1="218" x2="1340" y2="224" style="stroke: black;stroke-width:3px;clip-path:url(#stvwlhvkxelkveeokbghraomilekjpuo)"/>
<line x1="1330" y1="221" x2="1334" y2="227" style="stroke: black;stroke-width:3px;clip-path:url(#stvwlhvkxelkveeokbghraomilekjpuo)"/>
<line x1="1324" y1="224" x2="1328" y2="230" style="stroke: black;stroke-width:3px;clip-path:url(#stvwlhvkxelkveeokbghraomilekjpuo)"/>
<line x1="1350" y1="215" x2="1380" y2="230" style="stroke:black;stroke-width:2px"/>
<line x1="1380" y1="230" x2="1380" y2="260" style="stroke:black;stroke-width:2px"/>
<text x="1404" y="200" style="stroke:black">N</text>
<text x="1404" y="215" style="stroke:black">H</text>
<polyline points="1412,188 1440,170 1408,182" style="stroke:black;stroke-width:0;fill:black"/>
<line x1="1440" y1="170" x2="1470" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="1468" y1="185" x2="1468" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="1472" y1="185" x2="1472" y2="215" style="stroke:black;stroke-width:2px"/>
<text x="1464" y="230" style="stroke:black">O</text>
<line x1="1470" y1="185" x2="1500" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="1440" y1="170" x2="1440" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="1440" y1="140" x2="1470" y2="125" style="stroke:black;stroke-width:2px"/>
<line x1="1470" y1="125" x2="1500" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="1502" y1="134" x2="1526" y2="122" style="stroke:black;stroke-width:2px"/>
<line x1="1500" y1="140" x2="1530" y2="125" style="stroke:black;stroke-width:2px"/>
<line x1="1530" y1="125" x2="1530" y2="95" style="stroke:black;stroke-width:2px"/>
<line x1="1526" y1="98" x2="1502" y2="86" style="stroke:black;stroke-width:2px"/>
<line x1="1530" y1="95" x2="1500" y2="80" style="stroke:black;stroke-width:2px"/>
<line x1="1500" y1="80" x2="1470" y2="95" style="stroke:black;stroke-width:2px"/>
<line x1="1474" y1="98" x2="1474" y2="122" style="stroke:black;stroke-width:2px"/>
<line x1="1470" y1="95" x2="1470" y2="125" style="stroke:black;stroke-width:2px"/>
<line x1="1530" y1="95" x2="1560" y2="80" style="stroke:black;stroke-width:2px"/>
<text x="1563" y="87" style="stroke:black">O</text>
<text x="1573" y="87" style="stroke:black">H</text>
<text x="1494" y="167" style="stroke:black">N</text>
<text x="1494" y="152" style="stroke:black">H</text>
<clipPath id="pmpajyktwpzuvlnxuvzmztgycvxwsbph"><polyline points="1502,167 1530,185 1498,173" style="stroke:black;stroke-width:0;fill:black"/>
</clipPath>
<line x1="1498" y1="173" x2="1502" y2="167" style="stroke: black;stroke-width:3px;clip-path:url(#pmpajyktwpzuvlnxuvzmztgycvxwsbph)"/>
<line x1="1504" y1="176" x2="1508" y2="170" style="stroke: black;stroke-width:3px;clip-path:url(#pmpajyktwpzuvlnxuvzmztgycvxwsbph)"/>
<line x1="1510" y1="179" x2="1514" y2="173" style="stroke: black;stroke-width:3px;clip-path:url(#pmpajyktwpzuvlnxuvzmztgycvxwsbph)"/>
<line x1="1516" y1="182" x2="1520" y2="176" style="stroke: black;stroke-width:3px;clip-path:url(#pmpajyktwpzuvlnxuvzmztgycvxwsbph)"/>
<line x1="1522" y1="185" x2="1526" y2="179" style="stroke: black;stroke-width:3px;clip-path:url(#pmpajyktwpzuvlnxuvzmztgycvxwsbph)"/>
<line x1="1530" y1="185" x2="1560" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="1558" y1="170" x2="1558" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="1562" y1="170" x2="1562" y2="140" style="stroke:black;stroke-width:2px"/>
<text x="1554" y="137" style="stroke:black">O</text>
<line x1="1560" y1="170" x2="1590" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="1530" y1="185" x2="1530" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="1530" y1="215" x2="1560" y2="230" style="stroke:black;stroke-width:2px"/>
<line x1="1560" y1="230" x2="1560" y2="260" style="stroke:black;stroke-width:2px"/>
<line x1="1560" y1="230" x2="1590" y2="230" style="stroke:black;stroke-width:2px"/>
<text x="1584" y="200" style="stroke:black">N</text>
<text x="1584" y="215" style="stroke:black">H</text>
<polyline points="1592,188 1620,170 1588,182" style="stroke:black;stroke-width:0;fill:black"/>
<line x1="1620" y1="170" x2="1650" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="1648" y1="185" x2="1648" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="1652" y1="185" x2="1652" y2="215" style="stroke:black;stroke-width:2px"/>
<text x="1644" y="230" style="stroke:black">O</text>
<line x1="1650" y1="185" x2="1680" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="1620" y1="170" x2="1620" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="1620" y1="140" x2="1650" y2="125" style="stroke:black;stroke-width:2px"/>
<line x1="1650" y1="125" x2="1680" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="1682" y1="134" x2="1706" y2="122" style="stroke:black;stroke-width:2px"/>
<line x1="1680" y1="140" x2="1710" y2="125" style="stroke:black;stroke-width:2px"/>
<line x1="1710" y1="125" x2="1710" y2="95" style="stroke:black;stroke-width:2px"/>
<line x1="1706" y1="98" x2="1682" y2="86" style="stroke:black;stroke-width:2px"/>
<line x1="1710" y1="95" x2="1680" y2="80" style="stroke:black;stroke-width:2px"/>
<line x1="1680" y1="80" x2="1650" y2="95" style="stroke:black;stroke-width:2px"/>
<line x1="1654" y1="98" x2="1654" y2="122" style="stroke:black;stroke-width:2px"/>
<line x1="1650" y1="95" x2="1650" y2="125" style="stroke:black;stroke-width:2px"/>
<text x="1674" y="167" style="stroke:black">N</text>
<text x="1674" y="152" style="stroke:black">H</text>
<clipPath id="esegwfltdrjsiiddzjazgmlsoijwyzmh"><polyline points="1682,167 1710,185 1678,173" style="stroke:black;stroke-width:0;fill:black"/>
</clipPath>
<line x1="1678" y1="173" x2="1682" y2="167" style="stroke: black;stroke-width:3px;clip-path:url(#esegwfltdrjsiiddzjazgmlsoijwyzmh)"/>
<line x1="1684" y1="176" x2="1688" y2="170" style="stroke: black;stroke-width:3px;clip-path:url(#esegwfltdrjsiiddzjazgmlsoijwyzmh)"/>
<line x1="1690" y1="179" x2="1694" y2="173" style="stroke: black;stroke-width:3px;clip-path:url(#esegwfltdrjsiiddzjazgmlsoijwyzmh)"/>
<line x1="1696" y1="182" x2="1700" y2="176" style="stroke: black;stroke-width:3px;clip-path:url(#esegwfltdrjsiiddzjazgmlsoijwyzmh)"/>
<line x1="1702" y1="185" x2="1706" y2="179" style="stroke: black;stroke-width:3px;clip-path:url(#esegwfltdrjsiiddzjazgmlsoijwyzmh)"/>
<line x1="1710" y1="185" x2="1740" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="1738" y1="170" x2="1738" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="1742" y1="170" x2="1742" y2="140" style="stroke:black;stroke-width:2px"/>
<text x="1734" y="137" style="stroke:black">O</text>
<line x1="1740" y1="170" x2="1770" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="1710" y1="185" x2="1710" y2="215" style="stroke:black;stroke-width:2px"/>
<clipPath id="zogwidrbcmlbfmoymfjdjlctvwdpvgfb"><polyline points="1682,233 1710,215 1678,227" style="stroke:black;stroke-width:0;fill:black"/>
</clipPath>
<line x1="1708" y1="212" x2="1712" y2="218" style="stroke: black;stroke-width:3px;clip-path:url(#zogwidrbcmlbfmoymfjdjlctvwdpvgfb)"/>
<line x1="1702" y1="215" x2="1706" y2="221" style="stroke: black;stroke-width:3px;clip-path:url(#zogwidrbcmlbfmoymfjdjlctvwdpvgfb)"/>
<line x1="1696" y1="218" x2="1700" y2="224" style="stroke: black;stroke-width:3px;clip-path:url(#zogwidrbcmlbfmoymfjdjlctvwdpvgfb)"/>
<line x1="1690" y1="221" x2="1694" y2="227" style="stroke: black;stroke-width:3px;clip-path:url(#zogwidrbcmlbfmoymfjdjlctvwdpvgfb)"/>
<line x1="1684" y1="224" x2="1688" y2="230" style="stroke: black;stroke-width:3px;clip-path:url(#zogwidrbcmlbfmoymfjdjlctvwdpvgfb)"/>
<line x1="1710" y1="215" x2="1740" y2="230" style="stroke:black;stroke-width:2px"/>
<line x1="1740" y1="230" x2="1740" y2="260" style="stroke:black;stroke-width:2px"/>
<text x="1764" y="200" style="stroke:black">N</text>
<text x="1764" y="215" style="stroke:black">H</text>
<polyline points="1772,188 1800,170 1768,182" style="stroke:black;stroke-width:0;fill:black"/>
<line x1="1800" y1="170" x2="1830" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="1828" y1="185" x2="1828" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="1832" y1="185" x2="1832" y2="215" style="stroke:black;stroke-width:2px"/>
<text x="1824" y="230" style="stroke:black">O</text>
<line x1="1830" y1="185" x2="1860" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="1800" y1="170" x2="1800" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="1800" y1="140" x2="1830" y2="125" style="stroke:black;stroke-width:2px"/>
<line x1="1830" y1="125" x2="1860" y2="125" style="stroke:black;stroke-width:2px"/>
<text x="1863" y="132" style="stroke:black">O</text>
<text x="1876" y="126" style="stroke:black">-</text>
<line x1="1828" y1="125" x2="1828" y2="95" style="stroke:black;stroke-width:2px"/>
<line x1="1832" y1="125" x2="1832" y2="95" style="stroke:black;stroke-width:2px"/>
<text x="1824" y="92" style="stroke:black">O</text>
<text x="1854" y="167" style="stroke:black">N</text>
<text x="1854" y="152" style="stroke:black">H</text>
<clipPath id="jrgvfjcsdatfigpijsymyxdicwyngzgp"><polyline points="1862,167 1890,185 1858,173" style="stroke:black;stroke-width:0;fill:black"/>
</clipPath>
<line x1="1858" y1="173" x2="1862" y2="167" style="stroke: black;stroke-width:3px;clip-path:url(#jrgvfjcsdatfigpijsymyxdicwyngzgp)"/>
<line x1="1864" y1="176" x2="1868" y2="170" style="stroke: black;stroke-width:3px;clip-path:url(#jrgvfjcsdatfigpijsymyxdicwyngzgp)"/>
<line x1="1870" y1="179" x2="1874" y2="173" style="stroke: black;stroke-width:3px;clip-path:url(#jrgvfjcsdatfigpijsymyxdicwyngzgp)"/>
<line x1="1876" y1="182" x2="1880" y2="176" style="stroke: black;stroke-width:3px;clip-path:url(#jrgvfjcsdatfigpijsymyxdicwyngzgp)"/>
<line x1="1882" y1="185" x2="1886" y2="179" style="stroke: black;stroke-width:3px;clip-path:url(#jrgvfjcsdatfigpijsymyxdicwyngzgp)"/>
<line x1="1890" y1="185" x2="1920" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="1918" y1="170" x2="1918" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="1922" y1="170" x2="1922" y2="140" style="stroke:black;stroke-width:2px"/>
<text x="1914" y="137" style="stroke:black">O</text>
<line x1="1920" y1="170" x2="1950" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="1890" y1="185" x2="1890" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="1890" y1="215" x2="1920" y2="230" style="stroke:black;stroke-width:2px"/>
<line x1="1920" y1="230" x2="1920" y2="260" style="stroke:black;stroke-width:2px"/>
<line x1="1920" y1="260" x2="1950" y2="275" style="stroke:black;stroke-width:2px"/>
<text x="1953" y="282" style="stroke:black">N</text>
<text x="1963" y="282" style="stroke:black">H</text>
<text x="1977" y="282" style="font-size:8px;stroke:black">2</text>
<line x1="1920" y1="258" x2="1890" y2="273" style="stroke:black;stroke-width:2px"/>
<line x1="1920" y1="262" x2="1890" y2="277" style="stroke:black;stroke-width:2px"/>
<text x="1876" y="282" style="stroke:black">O</text>
<text x="1944" y="200" style="stroke:black">N</text>
<text x="1944" y="215" style="stroke:black">H</text>
<polyline points="1952,188 1980,170 1948,182" style="stroke:black;stroke-width:0;fill:black"/>
<line x1="1980" y1="170" x2="2010" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="2008" y1="185" x2="2008" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="2012" y1="185" x2="2012" y2="215" style="stroke:black;stroke-width:2px"/>
<text x="2004" y="230" style="stroke:black">O</text>
<line x1="2010" y1="185" x2="2040" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="1980" y1="170" x2="1980" y2="140" style="stroke:black;stroke-width:2px"/>
<polyline points="1952,122 1980,140 1948,128" style="stroke:black;stroke-width:0;fill:black"/>
<line x1="1980" y1="140" x2="2010" y2="125" style="stroke:black;stroke-width:2px"/>
<line x1="2010" y1="125" x2="2010" y2="95" style="stroke:black;stroke-width:2px"/>
<text x="2034" y="167" style="stroke:black">N</text>
<text x="2034" y="152" style="stroke:black">H</text>
<clipPath id="ghcceiflmmewtygpxvugzzvujhzhdzap"><polyline points="2042,167 2070,185 2038,173" style="stroke:black;stroke-width:0;fill:black"/>
</clipPath>
<line x1="2038" y1="173" x2="2042" y2="167" style="stroke: black;stroke-width:3px;clip-path:url(#ghcceiflmmewtygpxvugzzvujhzhdzap)"/>
<line x1="2044" y1="176" x2="2048" y2="170" style="stroke: black;stroke-width:3px;clip-path:url(#ghcceiflmmewtygpxvugzzvujhzhdzap)"/>
<line x1="2050" y1="179" x2="2054" y2="173" style="stroke: black;stroke-width:3px;clip-path:url(#ghcceiflmmewtygpxvugzzvujhzhdzap)"/>
<line x1="2056" y1="182" x2="2060" y2="176" style="stroke: black;stroke-width:3px;clip-path:url(#ghcceiflmmewtygpxvugzzvujhzhdzap)"/>
<line x1="2062" y1="185" x2="2066" y2="179" style="stroke: black;stroke-width:3px;clip-path:url(#ghcceiflmmewtygpxvugzzvujhzhdzap)"/>
<line x1="2070" y1="185" x2="2100" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="2098" y1="170" x2="2098" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="2102" y1="170" x2="2102" y2="140" style="stroke:black;stroke-width:2px"/>
<text x="2094" y="137" style="stroke:black">O</text>
<line x1="2100" y1="170" x2="2130" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="2070" y1="185" x2="2070" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="2070" y1="215" x2="2100" y2="230" style="stroke:black;stroke-width:2px"/>
<text x="2103" y="237" style="stroke:black">S</text>
<text x="2113" y="237" style="stroke:black">H</text>
<text x="2124" y="200" style="stroke:black">N</text>
<text x="2124" y="215" style="stroke:black">H</text>
<polyline points="2132,188 2160,170 2128,182" style="stroke:black;stroke-width:0;fill:black"/>
<line x1="2160" y1="170" x2="2190" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="2188" y1="185" x2="2188" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="2192" y1="185" x2="2192" y2="215" style="stroke:black;stroke-width:2px"/>
<text x="2184" y="230" style="stroke:black">O</text>
<line x1="2190" y1="185" x2="2220" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="2160" y1="170" x2="2160" y2="140" style="stroke:black;stroke-width:2px"/>
<polyline points="2132,122 2160,140 2128,128" style="stroke:black;stroke-width:0;fill:black"/>
<line x1="2160" y1="140" x2="2190" y2="125" style="stroke:black;stroke-width:2px"/>
<line x1="2190" y1="125" x2="2190" y2="95" style="stroke:black;stroke-width:2px"/>
<text x="2214" y="167" style="stroke:black">N</text>
<text x="2214" y="152" style="stroke:black">H</text>
<clipPath id="oovoggbkedvsxacmysjhffgzuyuxizkf"><polyline points="2222,167 2250,185 2218,173" style="stroke:black;stroke-width:0;fill:black"/>
</clipPath>
<line x1="2218" y1="173" x2="2222" y2="167" style="stroke: black;stroke-width:3px;clip-path:url(#oovoggbkedvsxacmysjhffgzuyuxizkf)"/>
<line x1="2224" y1="176" x2="2228" y2="170" style="stroke: black;stroke-width:3px;clip-path:url(#oovoggbkedvsxacmysjhffgzuyuxizkf)"/>
<line x1="2230" y1="179" x2="2234" y2="173" style="stroke: black;stroke-width:3px;clip-path:url(#oovoggbkedvsxacmysjhffgzuyuxizkf)"/>
<line x1="2236" y1="182" x2="2240" y2="176" style="stroke: black;stroke-width:3px;clip-path:url(#oovoggbkedvsxacmysjhffgzuyuxizkf)"/>
<line x1="2242" y1="185" x2="2246" y2="179" style="stroke: black;stroke-width:3px;clip-path:url(#oovoggbkedvsxacmysjhffgzuyuxizkf)"/>
<line x1="2250" y1="185" x2="2280" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="2278" y1="170" x2="2278" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="2282" y1="170" x2="2282" y2="140" style="stroke:black;stroke-width:2px"/>
<text x="2274" y="137" style="stroke:black">O</text>
<line x1="2280" y1="170" x2="2310" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="2250" y1="185" x2="2250" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="2250" y1="215" x2="2280" y2="230" style="stroke:black;stroke-width:2px"/>
<line x1="2280" y1="230" x2="2310" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="2312" y1="221" x2="2336" y2="233" style="stroke:black;stroke-width:2px"/>
<line x1="2310" y1="215" x2="2340" y2="230" style="stroke:black;stroke-width:2px"/>
<line x1="2340" y1="230" x2="2340" y2="260" style="stroke:black;stroke-width:2px"/>
<line x1="2336" y1="257" x2="2312" y2="269" style="stroke:black;stroke-width:2px"/>
<line x1="2340" y1="260" x2="2310" y2="275" style="stroke:black;stroke-width:2px"/>
<line x1="2310" y1="275" x2="2280" y2="260" style="stroke:black;stroke-width:2px"/>
<line x1="2284" y1="257" x2="2284" y2="233" style="stroke:black;stroke-width:2px"/>
<line x1="2280" y1="260" x2="2280" y2="230" style="stroke:black;stroke-width:2px"/>
<text x="2304" y="200" style="stroke:black">N</text>
<text x="2304" y="215" style="stroke:black">H</text>
<polyline points="2312,188 2340,170 2308,182" style="stroke:black;stroke-width:0;fill:black"/>
<line x1="2340" y1="170" x2="2370" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="2368" y1="185" x2="2368" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="2372" y1="185" x2="2372" y2="215" style="stroke:black;stroke-width:2px"/>
<text x="2364" y="230" style="stroke:black">O</text>
<line x1="2370" y1="185" x2="2400" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="2340" y1="170" x2="2340" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="2340" y1="140" x2="2370" y2="125" style="stroke:black;stroke-width:2px"/>
<line x1="2370" y1="125" x2="2400" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="2402" y1="134" x2="2426" y2="122" style="stroke:black;stroke-width:2px"/>
<line x1="2400" y1="140" x2="2430" y2="125" style="stroke:black;stroke-width:2px"/>
<line x1="2430" y1="125" x2="2430" y2="95" style="stroke:black;stroke-width:2px"/>
<line x1="2426" y1="98" x2="2402" y2="86" style="stroke:black;stroke-width:2px"/>
<line x1="2430" y1="95" x2="2400" y2="80" style="stroke:black;stroke-width:2px"/>
<line x1="2400" y1="80" x2="2370" y2="95" style="stroke:black;stroke-width:2px"/>
<line x1="2374" y1="98" x2="2374" y2="122" style="stroke:black;stroke-width:2px"/>
<line x1="2370" y1="95" x2="2370" y2="125" style="stroke:black;stroke-width:2px"/>
<line x1="2430" y1="95" x2="2460" y2="80" style="stroke:black;stroke-width:2px"/>
<text x="2463" y="87" style="stroke:black">O</text>
<text x="2473" y="87" style="stroke:black">H</text>
<text x="2394" y="167" style="stroke:black">N</text>
<text x="2394" y="152" style="stroke:black">H</text>
<clipPath id="voyajcvwiyjeewmbkwsbznvzbpywrakx"><polyline points="2402,167 2430,185 2398,173" style="stroke:black;stroke-width:0;fill:black"/>
</clipPath>
<line x1="2398" y1="173" x2="2402" y2="167" style="stroke: black;stroke-width:3px;clip-path:url(#voyajcvwiyjeewmbkwsbznvzbpywrakx)"/>
<line x1="2404" y1="176" x2="2408" y2="170" style="stroke: black;stroke-width:3px;clip-path:url(#voyajcvwiyjeewmbkwsbznvzbpywrakx)"/>
<line x1="2410" y1="179" x2="2414" y2="173" style="stroke: black;stroke-width:3px;clip-path:url(#voyajcvwiyjeewmbkwsbznvzbpywrakx)"/>
<line x1="2416" y1="182" x2="2420" y2="176" style="stroke: black;stroke-width:3px;clip-path:url(#voyajcvwiyjeewmbkwsbznvzbpywrakx)"/>
<line x1="2422" y1="185" x2="2426" y2="179" style="stroke: black;stroke-width:3px;clip-path:url(#voyajcvwiyjeewmbkwsbznvzbpywrakx)"/>
<line x1="2430" y1="185" x2="2460" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="2458" y1="170" x2="2458" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="2462" y1="170" x2="2462" y2="140" style="stroke:black;stroke-width:2px"/>
<text x="2454" y="137" style="stroke:black">O</text>
<line x1="2460" y1="170" x2="2490" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="2430" y1="185" x2="2430" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="2430" y1="215" x2="2460" y2="230" style="stroke:black;stroke-width:2px"/>
<line x1="2460" y1="230" x2="2490" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="2492" y1="221" x2="2516" y2="233" style="stroke:black;stroke-width:2px"/>
<line x1="2490" y1="215" x2="2520" y2="230" style="stroke:black;stroke-width:2px"/>
<line x1="2520" y1="230" x2="2520" y2="260" style="stroke:black;stroke-width:2px"/>
<line x1="2516" y1="257" x2="2492" y2="269" style="stroke:black;stroke-width:2px"/>
<line x1="2520" y1="260" x2="2490" y2="275" style="stroke:black;stroke-width:2px"/>
<line x1="2490" y1="275" x2="2460" y2="260" style="stroke:black;stroke-width:2px"/>
<line x1="2464" y1="257" x2="2464" y2="233" style="stroke:black;stroke-width:2px"/>
<line x1="2460" y1="260" x2="2460" y2="230" style="stroke:black;stroke-width:2px"/>
<text x="2484" y="200" style="stroke:black">N</text>
<text x="2484" y="215" style="stroke:black">H</text>
<polyline points="2492,188 2520,170 2488,182" style="stroke:black;stroke-width:0;fill:black"/>
<line x1="2520" y1="170" x2="2550" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="2548" y1="185" x2="2548" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="2552" y1="185" x2="2552" y2="215" style="stroke:black;stroke-width:2px"/>
<text x="2544" y="230" style="stroke:black">O</text>
<line x1="2550" y1="185" x2="2580" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="2520" y1="170" x2="2520" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="2520" y1="140" x2="2550" y2="125" style="stroke:black;stroke-width:2px"/>
<line x1="2550" y1="125" x2="2550" y2="95" style="stroke:black;stroke-width:2px"/>
<line x1="2550" y1="125" x2="2580" y2="125" style="stroke:black;stroke-width:2px"/>
<text x="2574" y="167" style="stroke:black">N</text>
<text x="2574" y="152" style="stroke:black">H</text>
<clipPath id="nojawwunlmnyabuaofbabjurnvrsouwz"><polyline points="2582,167 2610,185 2578,173" style="stroke:black;stroke-width:0;fill:black"/>
</clipPath>
<line x1="2578" y1="173" x2="2582" y2="167" style="stroke: black;stroke-width:3px;clip-path:url(#nojawwunlmnyabuaofbabjurnvrsouwz)"/>
<line x1="2584" y1="176" x2="2588" y2="170" style="stroke: black;stroke-width:3px;clip-path:url(#nojawwunlmnyabuaofbabjurnvrsouwz)"/>
<line x1="2590" y1="179" x2="2594" y2="173" style="stroke: black;stroke-width:3px;clip-path:url(#nojawwunlmnyabuaofbabjurnvrsouwz)"/>
<line x1="2596" y1="182" x2="2600" y2="176" style="stroke: black;stroke-width:3px;clip-path:url(#nojawwunlmnyabuaofbabjurnvrsouwz)"/>
<line x1="2602" y1="185" x2="2606" y2="179" style="stroke: black;stroke-width:3px;clip-path:url(#nojawwunlmnyabuaofbabjurnvrsouwz)"/>
<line x1="2610" y1="185" x2="2640" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="2638" y1="170" x2="2638" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="2642" y1="170" x2="2642" y2="140" style="stroke:black;stroke-width:2px"/>
<text x="2634" y="137" style="stroke:black">O</text>
<line x1="2640" y1="170" x2="2670" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="2610" y1="185" x2="2610" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="2610" y1="215" x2="2640" y2="230" style="stroke:black;stroke-width:2px"/>
<line x1="2640" y1="230" x2="2670" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="2672" y1="221" x2="2696" y2="233" style="stroke:black;stroke-width:2px"/>
<line x1="2670" y1="215" x2="2700" y2="230" style="stroke:black;stroke-width:2px"/>
<line x1="2700" y1="230" x2="2700" y2="260" style="stroke:black;stroke-width:2px"/>
<line x1="2696" y1="257" x2="2672" y2="269" style="stroke:black;stroke-width:2px"/>
<line x1="2700" y1="260" x2="2670" y2="275" style="stroke:black;stroke-width:2px"/>
<line x1="2670" y1="275" x2="2640" y2="260" style="stroke:black;stroke-width:2px"/>
<line x1="2644" y1="257" x2="2644" y2="233" style="stroke:black;stroke-width:2px"/>
<line x1="2640" y1="260" x2="2640" y2="230" style="stroke:black;stroke-width:2px"/>
<text x="2664" y="200" style="stroke:black">N</text>
<text x="2664" y="215" style="stroke:black">H</text>
<polyline points="2672,188 2700,170 2668,182" style="stroke:black;stroke-width:0;fill:black"/>
<line x1="2700" y1="170" x2="2730" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="2728" y1="185" x2="2728" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="2732" y1="185" x2="2732" y2="215" style="stroke:black;stroke-width:2px"/>
<text x="2724" y="230" style="stroke:black">O</text>
<line x1="2730" y1="185" x2="2760" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="2700" y1="170" x2="2700" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="2700" y1="140" x2="2730" y2="125" style="stroke:black;stroke-width:2px"/>
<line x1="2730" y1="125" x2="2760" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="2762" y1="134" x2="2786" y2="122" style="stroke:black;stroke-width:2px"/>
<line x1="2760" y1="140" x2="2790" y2="125" style="stroke:black;stroke-width:2px"/>
<line x1="2790" y1="125" x2="2790" y2="95" style="stroke:black;stroke-width:2px"/>
<line x1="2786" y1="98" x2="2762" y2="86" style="stroke:black;stroke-width:2px"/>
<line x1="2790" y1="95" x2="2760" y2="80" style="stroke:black;stroke-width:2px"/>
<line x1="2760" y1="80" x2="2730" y2="95" style="stroke:black;stroke-width:2px"/>
<line x1="2734" y1="98" x2="2734" y2="122" style="stroke:black;stroke-width:2px"/>
<line x1="2730" y1="95" x2="2730" y2="125" style="stroke:black;stroke-width:2px"/>
<text x="2754" y="167" style="stroke:black">N</text>
<text x="2754" y="152" style="stroke:black">H</text>
<clipPath id="baknokruhrnrxbfcnsiheaipcjcdmxum"><polyline points="2762,167 2790,185 2758,173" style="stroke:black;stroke-width:0;fill:black"/>
</clipPath>
<line x1="2758" y1="173" x2="2762" y2="167" style="stroke: black;stroke-width:3px;clip-path:url(#baknokruhrnrxbfcnsiheaipcjcdmxum)"/>
<line x1="2764" y1="176" x2="2768" y2="170" style="stroke: black;stroke-width:3px;clip-path:url(#baknokruhrnrxbfcnsiheaipcjcdmxum)"/>
<line x1="2770" y1="179" x2="2774" y2="173" style="stroke: black;stroke-width:3px;clip-path:url(#baknokruhrnrxbfcnsiheaipcjcdmxum)"/>
<line x1="2776" y1="182" x2="2780" y2="176" style="stroke: black;stroke-width:3px;clip-path:url(#baknokruhrnrxbfcnsiheaipcjcdmxum)"/>
<line x1="2782" y1="185" x2="2786" y2="179" style="stroke: black;stroke-width:3px;clip-path:url(#baknokruhrnrxbfcnsiheaipcjcdmxum)"/>
<line x1="2790" y1="185" x2="2820" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="2818" y1="170" x2="2818" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="2822" y1="170" x2="2822" y2="140" style="stroke:black;stroke-width:2px"/>
<text x="2814" y="137" style="stroke:black">O</text>
<line x1="2820" y1="170" x2="2850" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="2790" y1="185" x2="2790" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="2790" y1="215" x2="2820" y2="230" style="stroke:black;stroke-width:2px"/>
<line x1="2820" y1="230" x2="2850" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="2852" y1="221" x2="2876" y2="233" style="stroke:black;stroke-width:2px"/>
<line x1="2850" y1="215" x2="2880" y2="230" style="stroke:black;stroke-width:2px"/>
<line x1="2880" y1="230" x2="2880" y2="260" style="stroke:black;stroke-width:2px"/>
<line x1="2876" y1="257" x2="2852" y2="269" style="stroke:black;stroke-width:2px"/>
<line x1="2880" y1="260" x2="2850" y2="275" style="stroke:black;stroke-width:2px"/>
<line x1="2850" y1="275" x2="2820" y2="260" style="stroke:black;stroke-width:2px"/>
<line x1="2824" y1="257" x2="2824" y2="233" style="stroke:black;stroke-width:2px"/>
<line x1="2820" y1="260" x2="2820" y2="230" style="stroke:black;stroke-width:2px"/>
<text x="2844" y="200" style="stroke:black">N</text>
<text x="2844" y="215" style="stroke:black">H</text>
<polyline points="2852,188 2880,170 2848,182" style="stroke:black;stroke-width:0;fill:black"/>
<line x1="2880" y1="170" x2="2910" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="2908" y1="185" x2="2908" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="2912" y1="185" x2="2912" y2="215" style="stroke:black;stroke-width:2px"/>
<text x="2904" y="230" style="stroke:black">O</text>
<line x1="2910" y1="185" x2="2940" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="2880" y1="170" x2="2880" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="2880" y1="140" x2="2910" y2="125" style="stroke:black;stroke-width:2px"/>
<line x1="2880" y1="140" x2="2850" y2="125" style="stroke:black;stroke-width:2px"/>
<text x="2934" y="167" style="stroke:black">N</text>
<text x="2934" y="152" style="stroke:black">H</text>
<clipPath id="wjegooysoofudkukwnbdhjmiwappssry"><polyline points="2942,167 2970,185 2938,173" style="stroke:black;stroke-width:0;fill:black"/>
</clipPath>
<line x1="2938" y1="173" x2="2942" y2="167" style="stroke: black;stroke-width:3px;clip-path:url(#wjegooysoofudkukwnbdhjmiwappssry)"/>
<line x1="2944" y1="176" x2="2948" y2="170" style="stroke: black;stroke-width:3px;clip-path:url(#wjegooysoofudkukwnbdhjmiwappssry)"/>
<line x1="2950" y1="179" x2="2954" y2="173" style="stroke: black;stroke-width:3px;clip-path:url(#wjegooysoofudkukwnbdhjmiwappssry)"/>
<line x1="2956" y1="182" x2="2960" y2="176" style="stroke: black;stroke-width:3px;clip-path:url(#wjegooysoofudkukwnbdhjmiwappssry)"/>
<line x1="2962" y1="185" x2="2966" y2="179" style="stroke: black;stroke-width:3px;clip-path:url(#wjegooysoofudkukwnbdhjmiwappssry)"/>
<line x1="2970" y1="185" x2="3000" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="2998" y1="170" x2="2998" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="3002" y1="170" x2="3002" y2="140" style="stroke:black;stroke-width:2px"/>
<text x="2994" y="137" style="stroke:black">O</text>
<line x1="3000" y1="170" x2="3030" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="2970" y1="185" x2="2970" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="2970" y1="215" x2="3000" y2="230" style="stroke:black;stroke-width:2px"/>
<line x1="3000" y1="230" x2="3030" y2="230" style="stroke:black;stroke-width:2px"/>
<text x="3033" y="237" style="stroke:black">N</text>
<line x1="3030" y1="230" x2="3045" y2="260" style="stroke:black;stroke-width:2px"/>
<line x1="3026" y1="234" x2="3037" y2="256" style="stroke:black;stroke-width:2px"/>
<line x1="3045" y1="260" x2="3015" y2="275" style="stroke:black;stroke-width:2px"/>
<line x1="3000" y1="230" x2="2985" y2="260" style="stroke:black;stroke-width:2px"/>
<line x1="3004" y1="234" x2="2993" y2="256" style="stroke:black;stroke-width:2px"/>
<line x1="2985" y1="260" x2="3015" y2="275" style="stroke:black;stroke-width:2px"/>
<text x="3009" y="290" style="stroke:black">N</text>
<text x="3009" y="305" style="stroke:black">H</text>
<text x="3024" y="200" style="stroke:black">N</text>
<text x="3024" y="215" style="stroke:black">H</text>
<polyline points="3032,188 3060,170 3028,182" style="stroke:black;stroke-width:0;fill:black"/>
<line x1="3060" y1="170" x2="3090" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="3088" y1="185" x2="3088" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="3092" y1="185" x2="3092" y2="215" style="stroke:black;stroke-width:2px"/>
<text x="3084" y="230" style="stroke:black">O</text>
<line x1="3090" y1="185" x2="3120" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="3060" y1="170" x2="3060" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="3060" y1="140" x2="3090" y2="125" style="stroke:black;stroke-width:2px"/>
<line x1="3090" y1="125" x2="3120" y2="125" style="stroke:black;stroke-width:2px"/>
<text x="3123" y="132" style="stroke:black">N</text>
<line x1="3120" y1="125" x2="3135" y2="95" style="stroke:black;stroke-width:2px"/>
<line x1="3116" y1="121" x2="3127" y2="99" style="stroke:black;stroke-width:2px"/>
<line x1="3135" y1="95" x2="3105" y2="80" style="stroke:black;stroke-width:2px"/>
<line x1="3090" y1="125" x2="3075" y2="95" style="stroke:black;stroke-width:2px"/>
<line x1="3094" y1="121" x2="3083" y2="99" style="stroke:black;stroke-width:2px"/>
<line x1="3075" y1="95" x2="3105" y2="80" style="stroke:black;stroke-width:2px"/>
<text x="3099" y="77" style="stroke:black">N</text>
<text x="3099" y="62" style="stroke:black">H</text>
<text x="3114" y="167" style="stroke:black">N</text>
<text x="3114" y="152" style="stroke:black">H</text>
<line x1="3120" y1="170" x2="3150" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="3150" y1="185" x2="3180" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="3178" y1="170" x2="3178" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="3182" y1="170" x2="3182" y2="140" style="stroke:black;stroke-width:2px"/>
<text x="3174" y="137" style="stroke:black">O</text>
<line x1="3180" y1="170" x2="3210" y2="185" style="stroke:black;stroke-width:2px"/>
<text x="3204" y="200" style="stroke:black">N</text>
<text x="3204" y="215" style="stroke:black">H</text>
<polyline points="3212,188 3240,170 3208,182" style="stroke:black;stroke-width:0;fill:black"/>
<line x1="3240" y1="170" x2="3270" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="3268" y1="185" x2="3268" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="3272" y1="185" x2="3272" y2="215" style="stroke:black;stroke-width:2px"/>
<text x="3264" y="230" style="stroke:black">O</text>
<line x1="3270" y1="185" x2="3300" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="3240" y1="170" x2="3240" y2="140" style="stroke:black;stroke-width:2px"/>
<polyline points="3212,122 3240,140 3208,128" style="stroke:black;stroke-width:0;fill:black"/>
<line x1="3240" y1="140" x2="3270" y2="125" style="stroke:black;stroke-width:2px"/>
<line x1="3270" y1="125" x2="3270" y2="95" style="stroke:black;stroke-width:2px"/>
<text x="3294" y="167" style="stroke:black">N</text>
<text x="3294" y="152" style="stroke:black">H</text>
<clipPath id="bhmvrcifupuypshovhtbbwatmtbwnjtv"><polyline points="3302,167 3330,185 3298,173" style="stroke:black;stroke-width:0;fill:black"/>
</clipPath>
<line x1="3298" y1="173" x2="3302" y2="167" style="stroke: black;stroke-width:3px;clip-path:url(#bhmvrcifupuypshovhtbbwatmtbwnjtv)"/>
<line x1="3304" y1="176" x2="3308" y2="170" style="stroke: black;stroke-width:3px;clip-path:url(#bhmvrcifupuypshovhtbbwatmtbwnjtv)"/>
<line x1="3310" y1="179" x2="3314" y2="173" style="stroke: black;stroke-width:3px;clip-path:url(#bhmvrcifupuypshovhtbbwatmtbwnjtv)"/>
<line x1="3316" y1="182" x2="3320" y2="176" style="stroke: black;stroke-width:3px;clip-path:url(#bhmvrcifupuypshovhtbbwatmtbwnjtv)"/>
<line x1="3322" y1="185" x2="3326" y2="179" style="stroke: black;stroke-width:3px;clip-path:url(#bhmvrcifupuypshovhtbbwatmtbwnjtv)"/>
<line x1="3330" y1="185" x2="3360" y2="170" style="stroke:black;stroke-width:2px"/>
<line x1="3358" y1="170" x2="3358" y2="140" style="stroke:black;stroke-width:2px"/>
<line x1="3362" y1="170" x2="3362" y2="140" style="stroke:black;stroke-width:2px"/>
<text x="3354" y="137" style="stroke:black">O</text>
<line x1="3360" y1="170" x2="3390" y2="185" style="stroke:black;stroke-width:2px"/>
<line x1="3330" y1="185" x2="3330" y2="215" style="stroke:black;stroke-width:2px"/>
<line x1="3330" y1="215" x2="3360" y2="230" style="stroke:black;stroke-width:2px"/>
<line x1="3360" y1="230" x2="3360" y2="260" style="stroke:black;stroke-width:2px"/>
<line x1="3360" y1="230" x2="3390" y2="230" style="stroke:black;stroke-width:2px"/>
<text x="3393" y="192" style="stroke:black">O</text>
<text x="3406" y="186" style="stroke:black">-</text>
</svg>`)
}
